### ISSUE TITLE
May I ask something about link quality? (seek for help)

### ISSUE THREAD

**Issue by goldenfairy** [6e726d/PyWiWi#2]
Hi~hi, there is a  'link quality' in WindowsNativeWifiApi.py in line 261,  and I can't find it's official definition.How it is defined in this  program? 
By the way, thank you very much for openning this program, it's helpful for me.^_^

**Comment by 6e726d** [comment]
The member you are mentioning is the uLinkQuality from the WLAN_BSS_ENTRY structure. This member has the link quality reported by the wireless LAN interface driver. The link quality value ranges from 0 through 100. A value of 100 specifies the highest link quality.

For more information on this structure please visit this link (https://msdn.microsoft.com/en-us/library/windows/desktop/ms706839%28v=vs.85%29.aspx).
